FROM golang:1.24-alpine

WORKDIR /srv

RUN mkdir ./app

WORKDIR /srv/app

COPY ./app/go.mod ./app/go.sum ./

RUN go mod download
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

COPY ./app ./

ENV PATH="/go/bin:${PATH}"

EXPOSE 80

CMD ["go", "run", "cmd/main.go"]
