# Stage 1: Build
FROM golang:1.24-alpine AS builder

WORKDIR /srv

RUN mkdir ./app

WORKDIR /srv/app

COPY ./app/go.mod ./app/go.sum ./

RUN go mod download

RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

COPY ./app ./
RUN go build -o main .

# Stage 2: Run
FROM alpine:latest
WORKDIR /srv

COPY --from=builder /srv/main .

ENV PATH="/go/bin:${PATH}"

EXPOSE 80
CMD ["./main"]
