x-go-tmpl: &go-tmpl
  image: vaross/private-projects:shortify-prod-latest
  restart: always
  platform: linux/amd64
  working_dir: /srv/app
  volumes:
    - ./:/srv/:rw
  env_file:
    - .env
  networks:
    - shortify-network
  command: go run cmd/main.go
  
services:
  shortify-nginx:
    container_name: shortify-nginx
    image: nginx:1.27-alpine
    platform: linux/amd64
    restart: always
    ports:
      - 81:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shortify-network
    depends_on:
      - shortify-backend

  shortify-backend:
    <<: *go-tmpl
    container_name: shortify-backend

  shortify-postgres:
    container_name: shortify-postgres
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - shortify-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shortify-network

  shortify-redis:
    image: redis:7.2
    container_name: shortify-redis
    ports:
      - "6379:6379"
    volumes:
      - shortify-redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    networks:
      - shortify-network

volumes:
  shortify-postgres-data:
    driver: local
  shortify-redis-data:
    driver: local

networks:
  shortify-network:
    name: shortify-network
    driver: bridge
